#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

script:
  - mkdir _data
  - ./build-site-data.sh _data/apps.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  name: Travis CI Deployment Bot
  on:
    branch: master
